-- RAW_SUPPLIES Table DDL
-- Jaffle Shop Supply/Ingredient Master Data

CREATE TABLE IF NOT EXISTS RAW_SUPPLIES (
    ID VARCHAR NOT NULL,
    NAME VARCHAR NOT NULL,
    COST NUMBER(10, 2),
    PERISHABLE VARCHAR,
    SKU VARCHAR NOT NULL
);
