WITH RAW_PRODUCTS AS (
SELECT * 
FROM JAFFELSHOP_ECOM.PUBLIC.RAW_PRODUCTS
)

SELECT  SKU  AS PRODUCT_SKU ,
        NAME AS PRODUCT_NAME ,
        TYPE AS PRODUCT_TYPE ,
        PRICE AS PRODUCT_PRICE ,
        DESCRIPTION AS PRODUCT_DESCRIPTION 
FROM RAW_PRODUCTS

