sources:
  - name: snapshot_demo
    database: SNAPSHOT_DEMO
    schema: PUBLIC
    tables:
      - name: ord_status
        identifier: order_status
        
      - name: prd_version
        identifier: product_version
      
      - name: emp_dept
        identifier: EMPLOYEE_DEPT

      - name: emp_sal
        identifier: EMPLOYEE_SALARY
      