-- RAW_ORDERS Table DDL (Customer Orders)
-- Jaffle Shop Order Transaction Data

CREATE TABLE IF NOT EXISTS RAW_ORDERS (
    ID VARCHAR NOT NULL,
    CUSTOMER VARCHAR NOT NULL,
    ORDERED_AT VARCHAR,
    STORE_ID VARCHAR NOT NULL,
    SUBTOTAL INTEGER,
    TAX_PAID INTEGER,
    ORDER_TOTAL INTEGER
);
