-- RAW_PRODUCTS Table DDL
-- Jaffle Shop Product/Menu Master Data

CREATE TABLE IF NOT EXISTS RAW_PRODUCTS (
    SKU VARCHAR NOT NULL,
    NAME VARCHAR NOT NULL,
    TYPE VARCHAR,
    PRICE NUMBER(10, 2),
    DESCRIPTION VARCHAR
);
