-- RAW_ITEMS Table DDL (Order Items)
-- Jaffle Shop Order Line Items Data

CREATE TABLE IF NOT EXISTS RAW_ITEMS (
    ID VARCHAR NOT NULL,
    ORDER_ID VARCHAR NOT NULL,
    SKU VARCHAR NOT NULL,
    QUANTITY INTEGER,
    PRICE NUMBER(10, 2)
);
