-- RAW_STORES Table DDL
-- Jaffle Shop Store Master Data

CREATE TABLE IF NOT EXISTS RAW_STORES (
    ID VARCHAR NOT NULL,
    NAME VARCHAR NOT NULL,
    OPENED_AT VARCHAR,
    TAX_RATE NUMBER(5, 4)
);
