WITH RAW_PRODUCTS AS (
    SELECT * FROM {{ source('raw', 'raw_products') }}
)

SELECT  SKU         AS PRODUCT_SKU, 
        NAME        AS PRODUCT_NAME, 
        TYPE        AS PRODUCT_TYPE, 
        PRICE       AS PRODUCT_PRICE, 
        ROUND(PRICE / 100.0, 2) AS PRODUCT_PRICE_DOLLARS,
        DESCRIPTION AS PRODUCT_DESCRIPTION,
        CURRENT_TIMESTAMP() AS CREATED_AT
FROM RAW_PRODUCTS
WHERE SKU IS NOT NULL