WITH RAW_PRODUCTS AS (
    SELECT 
        SKU,
        NAME,
        TYPE,
        PRICE,
        DESCRIPTION,
        TRY_CAST(PRICE AS DECIMAL(10, 2)) as PRICE_NUMERIC
    FROM {{ source('raw', 'raw_products') }}
),
VALID_PRODUCTS AS (
    SELECT *
    FROM RAW_PRODUCTS
    WHERE PRICE_NUMERIC IS NOT NULL
)

SELECT  SKU         AS PRODUCT_SKU, 
        NAME        AS PRODUCT_NAME, 
        TYPE        AS PRODUCT_TYPE, 
        PRICE_NUMERIC AS PRODUCT_PRICE,
        ROUND(PRICE_NUMERIC / 100.0, 2) AS PRODUCT_PRICE_DOLLARS,
        DESCRIPTION AS PRODUCT_DESCRIPTION,
        CURRENT_TIMESTAMP() AS CREATED_AT
FROM VALID_PRODUCTS
WHERE SKU IS NOT NULL