WITH CUSTOMERS AS (
SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME
FROM {{ source('raw', 'raw_customers') }}
)

SELECT  
    CUSTOMER_ID,
    CUSTOMER_NAME,
    SPLIT_PART(CUSTOMER_NAME, ' ', 1) as FIRST_NAME,
    CASE 
        WHEN ARRAY_SIZE(SPLIT(CUSTOMER_NAME, ' ')) = 3 THEN SPLIT_PART(CUSTOMER_NAME, ' ', 2)
        ELSE NULL
    END as MIDDLE_NAME,
    SPLIT_PART(CUSTOMER_NAME, ' ', -1) as LAST_NAME
FROM CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL