WITH RAW_ORDERS AS (
SELECT * FROM {{ source('raw', 'raw_orders') }}
)

SELECT  ID as ORDER_ID, 
        CUSTOMER as ORDER_CUSTOMER, 
        ORDERED_AT, 
        STORE_ID AS ORDER_STORE_ID, 
        SUBTOTAL AS ORDER_SUBTOTAL, 
        TAX_PAID AS ORDER_TAX_PAID, 
        ORDER_TOTAL 
FROM RAW_ORDERS
WHERE ID IS NOT NULL
