-- ============================================================================
-- SALES & ORDER ANALYSIS QUERIES
-- ============================================================================

-- 1. DAILY SALES SUMMARY
-- Revenue trends by day
SELECT 
    ORDER_DATE,
    DAYNAME(ORDER_DATE) as DAY_NAME,
    COUNT(DISTINCT ORDER_ID) as TOTAL_ORDERS,
    COUNT(DISTINCT ORDER_CUSTOMER) as UNIQUE_CUSTOMERS,
    SUM(ORDER_TOTAL) as DAILY_REVENUE,
    ROUND(AVG(ORDER_TOTAL), 2) as AVG_ORDER_VALUE,
    SUM(ITEMS_IN_ORDER) as TOTAL_ITEMS_SOLD,
    ROUND(AVG(ITEMS_IN_ORDER), 2) as AVG_ITEMS_PER_ORDER,
    SUM(ORDER_TAX_PAID) as TAX_COLLECTED,
    ROUND(AVG(TAX_RATE_PERCENT), 2) as AVG_TAX_RATE
FROM {{ ref('mart_orders') }}
WHERE ORDER_DATE IS NOT NULL
GROUP BY ORDER_DATE, DAYNAME(ORDER_DATE)
ORDER BY ORDER_DATE DESC;

-- ============================================================================

-- 2. MONTHLY SALES TRENDS
-- Revenue by month for year-over-year analysis
SELECT 
    ORDER_YEAR,
    ORDER_MONTH,
    MONTHNAME(DATEFROMPARTS(ORDER_YEAR, ORDER_MONTH, 1)) as MONTH_NAME,
    COUNT(DISTINCT ORDER_ID) as TOTAL_ORDERS,
    COUNT(DISTINCT ORDER_CUSTOMER) as UNIQUE_CUSTOMERS,
    SUM(ORDER_TOTAL) as MONTHLY_REVENUE,
    ROUND(AVG(ORDER_TOTAL), 2) as AVG_ORDER_VALUE,
    SUM(ITEMS_IN_ORDER) as TOTAL_UNITS_SOLD,
    ROUND(SUM(ORDER_TOTAL) / NULLIF(COUNT(DISTINCT ORDER_ID), 0), 2) as REVENUE_PER_ORDER,
    COUNT(DISTINCT ORDER_ID) / NULLIF(COUNT(DISTINCT ORDER_CUSTOMER), 0) as ORDERS_PER_CUSTOMER
FROM {{ ref('mart_orders') }}
WHERE ORDER_DATE IS NOT NULL
GROUP BY ORDER_YEAR, ORDER_MONTH
ORDER BY ORDER_YEAR DESC, ORDER_MONTH DESC;

-- ============================================================================

-- 3. PEAK HOUR ANALYSIS
-- Identify busiest shopping hours
SELECT 
    ORDER_HOUR,
    CASE 
        WHEN ORDER_HOUR < 6 THEN 'Night (00:00-05:59)'
        WHEN ORDER_HOUR < 12 THEN 'Morning (06:00-11:59)'
        WHEN ORDER_HOUR < 18 THEN 'Afternoon (12:00-17:59)'
        ELSE 'Evening (18:00-23:59)'
    END as TIME_OF_DAY,
    COUNT(DISTINCT ORDER_ID) as ORDER_COUNT,
    SUM(ORDER_TOTAL) as HOURLY_REVENUE,
    ROUND(AVG(ORDER_TOTAL), 2) as AVG_ORDER_VALUE,
    SUM(ITEMS_IN_ORDER) as ITEMS_SOLD,
    ROUND(COUNT(DISTINCT ORDER_ID) / NULLIF(COUNT(DISTINCT ORDER_CUSTOMER), 0), 2) as ORDERS_PER_CUSTOMER
FROM {{ ref('mart_orders') }}
WHERE ORDER_HOUR IS NOT NULL
GROUP BY ORDER_HOUR, TIME_OF_DAY
ORDER BY HOURLY_REVENUE DESC;

-- ============================================================================

-- 4. ORDER VALUE DISTRIBUTION
-- Breakdown of orders by value segment
SELECT 
    ORDER_VALUE_SEGMENT,
    ORDER_TYPE,
    COUNT(DISTINCT ORDER_ID) as ORDER_COUNT,
    ROUND(100.0 * COUNT(DISTINCT ORDER_ID) / SUM(COUNT(DISTINCT ORDER_ID)) OVER (), 2) as PERCENT_OF_ORDERS,
    SUM(ORDER_TOTAL) as SEGMENT_REVENUE,
    ROUND(100.0 * SUM(ORDER_TOTAL) / SUM(SUM(ORDER_TOTAL)) OVER (), 2) as PERCENT_OF_REVENUE,
    ROUND(AVG(ORDER_TOTAL), 2) as AVG_ORDER_VALUE,
    ROUND(AVG(ITEMS_IN_ORDER), 2) as AVG_ITEMS,
    MIN(ORDER_TOTAL) as MIN_ORDER_VALUE,
    MAX(ORDER_TOTAL) as MAX_ORDER_VALUE
FROM {{ ref('mart_orders') }}
WHERE ORDER_VALUE_SEGMENT IS NOT NULL
GROUP BY ORDER_VALUE_SEGMENT, ORDER_TYPE
ORDER BY PERCENT_OF_REVENUE DESC;

-- ============================================================================

-- 5. CUSTOMER REPEAT PURCHASE ANALYSIS
-- How often customers reorder
SELECT 
    CASE 
        WHEN RECENCY_RANK = 1 THEN 'Most Recent'
        WHEN RECENCY_RANK <= 5 THEN 'Recent Buyer'
        ELSE 'Past Buyer'
    END as PURCHASE_RECENCY_SEGMENT,
    COUNT(DISTINCT ORDER_CUSTOMER) as CUSTOMER_COUNT,
    COUNT(DISTINCT ORDER_ID) as TOTAL_ORDERS,
    ROUND(COUNT(DISTINCT ORDER_ID) / NULLIF(COUNT(DISTINCT ORDER_CUSTOMER), 0), 2) as AVG_ORDERS_PER_CUSTOMER,
    SUM(ORDER_TOTAL) as SEGMENT_REVENUE,
    ROUND(AVG(ORDER_TOTAL), 2) as AVG_ORDER_VALUE,
    ROUND(AVG(ITEMS_IN_ORDER), 2) as AVG_ITEMS_PER_ORDER
FROM {{ ref('mart_orders_by_customer') }}
WHERE ORDER_ID IS NOT NULL
GROUP BY PURCHASE_RECENCY_SEGMENT
ORDER BY AVG_ORDERS_PER_CUSTOMER DESC;

-- ============================================================================

-- 6. DAY OF WEEK PERFORMANCE
-- Which days drive the most sales
SELECT 
    ORDER_DAY_OF_WEEK,
    CASE ORDER_DAY_OF_WEEK
        WHEN 1 THEN 'Sunday'
        WHEN 2 THEN 'Monday'
        WHEN 3 THEN 'Tuesday'
        WHEN 4 THEN 'Wednesday'
        WHEN 5 THEN 'Thursday'
        WHEN 6 THEN 'Friday'
        WHEN 7 THEN 'Saturday'
    END as DAY_NAME,
    COUNT(DISTINCT ORDER_ID) as ORDER_COUNT,
    SUM(ORDER_TOTAL) as DAILY_REVENUE,
    ROUND(AVG(ORDER_TOTAL), 2) as AVG_ORDER_VALUE,
    ROUND(SUM(ORDER_TOTAL) / COUNT(DISTINCT ORDER_ID), 2) as REVENUE_PER_ORDER,
    ROUND(AVG(ITEMS_IN_ORDER), 2) as AVG_ITEMS
FROM {{ ref('mart_orders') }}
WHERE ORDER_DAY_OF_WEEK IS NOT NULL
GROUP BY ORDER_DAY_OF_WEEK
ORDER BY DAILY_REVENUE DESC;

-- ============================================================================

-- 7. STORE PERFORMANCE
-- Sales by store location
SELECT 
    ORDER_STORE_ID,
    COUNT(DISTINCT ORDER_ID) as TOTAL_ORDERS,
    COUNT(DISTINCT ORDER_CUSTOMER) as UNIQUE_CUSTOMERS,
    SUM(ORDER_TOTAL) as STORE_REVENUE,
    ROUND(AVG(ORDER_TOTAL), 2) as AVG_ORDER_VALUE,
    ROUND(SUM(ORDER_TOTAL) / COUNT(DISTINCT ORDER_ID), 2) as REVENUE_PER_ORDER,
    ROUND(SUM(ORDER_TOTAL) / NULLIF(COUNT(DISTINCT ORDER_CUSTOMER), 0), 2) as REVENUE_PER_CUSTOMER,
    MIN(CAST(ORDERED_AT AS DATE)) as FIRST_ORDER_DATE,
    MAX(CAST(ORDERED_AT AS DATE)) as LAST_ORDER_DATE
FROM {{ ref('mart_orders') }}
WHERE ORDER_STORE_ID IS NOT NULL
GROUP BY ORDER_STORE_ID
ORDER BY STORE_REVENUE DESC;
