-- ============================================================================
-- ADVANCED ANALYTICS & INSIGHTS
-- ============================================================================

-- 1. RFM ANALYSIS (RECENCY, FREQUENCY, MONETARY)
-- Segment customers using classic RFM scoring
WITH CUSTOMER_RFM AS (
    SELECT 
        CUSTOMER_ID,
        CUSTOMER_NAME,
        RECENCY_DAYS,
        TOTAL_ORDERS as FREQUENCY,
        CUSTOMER_LIFETIME_VALUE as MONETARY,
        NTILE(5) OVER (ORDER BY RECENCY_DAYS DESC) as RECENCY_SCORE,
        NTILE(5) OVER (ORDER BY TOTAL_ORDERS ASC) as FREQUENCY_SCORE,
        NTILE(5) OVER (ORDER BY CUSTOMER_LIFETIME_VALUE ASC) as MONETARY_SCORE
    FROM {{ ref('mart_customers') }}
    WHERE CUSTOMER_ID IS NOT NULL
)
SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    RECENCY_DAYS,
    FREQUENCY,
    MONETARY,
    RECENCY_SCORE,
    FREQUENCY_SCORE,
    MONETARY_SCORE,
    (RECENCY_SCORE + FREQUENCY_SCORE + MONETARY_SCORE) as RFM_TOTAL_SCORE,
    CASE 
        WHEN (RECENCY_SCORE + FREQUENCY_SCORE + MONETARY_SCORE) >= 13 THEN 'Champions'
        WHEN (RECENCY_SCORE + FREQUENCY_SCORE + MONETARY_SCORE) >= 10 THEN 'Loyal Customers'
        WHEN (RECENCY_SCORE + FREQUENCY_SCORE + MONETARY_SCORE) >= 7 THEN 'Potential Loyalists'
        WHEN RECENCY_SCORE >= 4 THEN 'Recent Customers'
        ELSE 'At Risk / Dormant'
    END as RFM_SEGMENT
FROM CUSTOMER_RFM
ORDER BY RFM_TOTAL_SCORE DESC;

-- ============================================================================

-- 2. CUSTOMER LIFETIME VALUE PROJECTION
-- Estimate future revenue based on past behavior
SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_LIFETIME_VALUE,
    TOTAL_ORDERS,
    AVG_ORDER_VALUE,
    CUSTOMER_TENURE_DAYS,
    CUSTOMER_ORDER_FREQUENCY_ANNUAL,
    ROUND(AVG_ORDER_VALUE * CUSTOMER_ORDER_FREQUENCY_ANNUAL * 2, 2) as PROJECTED_CLV_2_YEARS,
    ROUND(AVG_ORDER_VALUE * CUSTOMER_ORDER_FREQUENCY_ANNUAL * 3, 2) as PROJECTED_CLV_3_YEARS,
    CASE 
        WHEN CUSTOMER_ORDER_FREQUENCY_ANNUAL >= 12 THEN 'High Engagement'
        WHEN CUSTOMER_ORDER_FREQUENCY_ANNUAL >= 4 THEN 'Medium Engagement'
        ELSE 'Low Engagement'
    END as ENGAGEMENT_LEVEL
FROM {{ ref('mart_customers') }}
WHERE CUSTOMER_ID IS NOT NULL
  AND CUSTOMER_ORDER_FREQUENCY_ANNUAL > 0
ORDER BY PROJECTED_CLV_3_YEARS DESC;

-- ============================================================================

-- 3. CUSTOMER COHORT ANALYSIS
-- Track customer behavior by acquisition cohort
WITH CUSTOMER_COHORTS AS (
    SELECT 
        DATE_TRUNC(MONTH, FIRST_ORDER_DATE) as COHORT_MONTH,
        CUSTOMER_ID,
        CUSTOMER_NAME,
        CUSTOMER_LIFETIME_VALUE,
        TOTAL_ORDERS,
        CUSTOMER_STATUS
    FROM {{ ref('mart_customers') }}
    WHERE CUSTOMER_ID IS NOT NULL
)
SELECT 
    COHORT_MONTH,
    COUNT(DISTINCT CUSTOMER_ID) as COHORT_SIZE,
    COUNT(DISTINCT CASE WHEN CUSTOMER_STATUS = 'Active' THEN CUSTOMER_ID END) as ACTIVE_CUSTOMERS,
    ROUND(100.0 * COUNT(DISTINCT CASE WHEN CUSTOMER_STATUS = 'Active' THEN CUSTOMER_ID END) 
        / NULLIF(COUNT(DISTINCT CUSTOMER_ID), 0), 2) as RETENTION_RATE,
    ROUND(SUM(CUSTOMER_LIFETIME_VALUE) / NULLIF(COUNT(DISTINCT CUSTOMER_ID), 0), 2) as AVG_CLV_PER_CUSTOMER,
    ROUND(AVG(TOTAL_ORDERS), 2) as AVG_ORDERS,
    SUM(CUSTOMER_LIFETIME_VALUE) as COHORT_TOTAL_VALUE
FROM CUSTOMER_COHORTS
GROUP BY COHORT_MONTH
ORDER BY COHORT_MONTH DESC;

-- ============================================================================

-- 4. CHURN RISK SCORING
-- Identify customers most likely to leave
SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_LIFETIME_VALUE,
    TOTAL_ORDERS,
    RECENCY_DAYS,
    CUSTOMER_TENURE_DAYS,
    AVG_ORDER_VALUE,
    LAST_ORDER_DATE,
    CASE 
        WHEN RECENCY_DAYS > (CUSTOMER_TENURE_DAYS / 2) THEN 'HIGH RISK'
        WHEN RECENCY_DAYS > (CUSTOMER_TENURE_DAYS / 3) THEN 'MEDIUM RISK'
        ELSE 'LOW RISK'
    END as CHURN_RISK,
    ROUND(RECENCY_DAYS / NULLIF(CUSTOMER_TENURE_DAYS, 0), 2) as INACTIVE_RATIO,
    DATEDIFF(DAY, LAST_ORDER_DATE, CURRENT_DATE()) as DAYS_INACTIVE
FROM {{ ref('mart_customers') }}
WHERE CUSTOMER_ID IS NOT NULL
  AND TOTAL_ORDERS > 1
  AND CUSTOMER_STATUS != 'Active'
ORDER BY RECENCY_DAYS DESC;

-- ============================================================================

-- 5. REVENUE GROWTH ANALYSIS
-- Month-over-month growth trends
WITH MONTHLY_REVENUE AS (
    SELECT 
        ORDER_YEAR,
        ORDER_MONTH,
        SUM(ORDER_TOTAL) as MONTHLY_REVENUE,
        COUNT(DISTINCT ORDER_ID) as MONTHLY_ORDERS,
        COUNT(DISTINCT ORDER_CUSTOMER) as MONTHLY_CUSTOMERS
    FROM {{ ref('mart_orders') }}
    WHERE ORDER_DATE IS NOT NULL
    GROUP BY ORDER_YEAR, ORDER_MONTH
)
SELECT 
    ORDER_YEAR,
    ORDER_MONTH,
    MONTHLY_REVENUE,
    LAG(MONTHLY_REVENUE) OVER (ORDER BY ORDER_YEAR, ORDER_MONTH) as PREV_MONTH_REVENUE,
    ROUND(((MONTHLY_REVENUE - LAG(MONTHLY_REVENUE) OVER (ORDER BY ORDER_YEAR, ORDER_MONTH)) 
        / NULLIF(LAG(MONTHLY_REVENUE) OVER (ORDER BY ORDER_YEAR, ORDER_MONTH), 0)) * 100, 2) as MOM_GROWTH_PERCENT,
    MONTHLY_ORDERS,
    MONTHLY_CUSTOMERS,
    ROUND(MONTHLY_REVENUE / NULLIF(MONTHLY_ORDERS, 0), 2) as AVG_ORDER_VALUE
FROM MONTHLY_REVENUE
ORDER BY ORDER_YEAR DESC, ORDER_MONTH DESC;

-- ============================================================================

-- 6. CUSTOMER-PRODUCT AFFINITY
-- Which customer segments buy which products
WITH CUSTOMER_PRODUCT_AFFINITY AS (
    SELECT 
        c.CUSTOMER_SEGMENT,
        c.CUSTOMER_STATUS,
        oi.PRODUCT_NAME,
        oi.PRODUCT_TYPE,
        COUNT(DISTINCT oi.ORDER_ID) as PURCHASE_COUNT,
        SUM(oi.ITEM_AMOUNT) as SEGMENT_PRODUCT_REVENUE,
        COUNT(DISTINCT c.CUSTOMER_ID) as CUSTOMER_COUNT
    FROM {{ ref('mart_orders_by_customer') }} oc
    INNER JOIN {{ ref('mart_customers') }} c ON oc.CUSTOMER_ID = c.CUSTOMER_ID
    INNER JOIN {{ ref('int_orders_items_joined') }} oi ON oc.ORDER_ID = oi.ORDER_ID
    WHERE oc.ORDER_ID IS NOT NULL
    GROUP BY c.CUSTOMER_SEGMENT, c.CUSTOMER_STATUS, oi.PRODUCT_NAME, oi.PRODUCT_TYPE
)
SELECT 
    CUSTOMER_SEGMENT,
    CUSTOMER_STATUS,
    PRODUCT_NAME,
    PRODUCT_TYPE,
    PURCHASE_COUNT,
    ROUND(SEGMENT_PRODUCT_REVENUE, 2) as REVENUE,
    CUSTOMER_COUNT,
    RANK() OVER (PARTITION BY CUSTOMER_SEGMENT, CUSTOMER_STATUS ORDER BY SEGMENT_PRODUCT_REVENUE DESC) as PRODUCT_RANK
FROM CUSTOMER_PRODUCT_AFFINITY
WHERE PRODUCT_RANK <= 10
ORDER BY CUSTOMER_SEGMENT, CUSTOMER_STATUS, PRODUCT_RANK;

-- ============================================================================

-- 7. BASKET ANALYSIS
-- Average order composition and value
WITH BASKET_METRICS AS (
    SELECT 
        ORDER_ID,
        ORDER_CUSTOMER,
        ORDER_TOTAL,
        COUNT(DISTINCT ITEM_SKU) as UNIQUE_PRODUCTS,
        COUNT(ITEM_ID) as TOTAL_ITEMS,
        COUNT(DISTINCT PRODUCT_TYPE) as PRODUCT_TYPES
    FROM {{ ref('int_orders_items_joined') }}
    GROUP BY ORDER_ID, ORDER_CUSTOMER, ORDER_TOTAL
)
SELECT 
    CASE 
        WHEN UNIQUE_PRODUCTS = 1 THEN 'Single Product'
        WHEN UNIQUE_PRODUCTS BETWEEN 2 AND 3 THEN '2-3 Products'
        WHEN UNIQUE_PRODUCTS BETWEEN 4 AND 5 THEN '4-5 Products'
        ELSE '6+ Products'
    END as BASKET_COMPOSITION,
    COUNT(DISTINCT ORDER_ID) as BASKET_COUNT,
    ROUND(100.0 * COUNT(DISTINCT ORDER_ID) / SUM(COUNT(DISTINCT ORDER_ID)) OVER (), 2) as PERCENT_OF_ORDERS,
    ROUND(AVG(ORDER_TOTAL), 2) as AVG_BASKET_VALUE,
    ROUND(AVG(TOTAL_ITEMS), 2) as AVG_ITEMS_PER_BASKET,
    MIN(ORDER_TOTAL) as MIN_BASKET_VALUE,
    MAX(ORDER_TOTAL) as MAX_BASKET_VALUE,
    SUM(ORDER_TOTAL) as TOTAL_REVENUE
FROM BASKET_METRICS
GROUP BY BASKET_COMPOSITION
ORDER BY AVG_BASKET_VALUE DESC;
