-- ============================================================================
-- EXECUTIVE SUMMARY DASHBOARDS & KPIs
-- ============================================================================

-- 1. EXECUTIVE SUMMARY - KEY METRICS SNAPSHOT
-- High-level KPIs for business stakeholders
SELECT 
    -- Customer Metrics
    (SELECT COUNT(DISTINCT CUSTOMER_ID) FROM {{ ref('mart_customers') }} WHERE CUSTOMER_ID IS NOT NULL) as TOTAL_CUSTOMERS,
    (SELECT COUNT(DISTINCT CUSTOMER_ID) FROM {{ ref('mart_customers') }} WHERE CUSTOMER_STATUS = 'Active') as ACTIVE_CUSTOMERS,
    (SELECT COUNT(DISTINCT CUSTOMER_ID) FROM {{ ref('mart_customers') }} WHERE CUSTOMER_STATUS = 'At Risk') as AT_RISK_CUSTOMERS,
    (SELECT ROUND(AVG(CUSTOMER_LIFETIME_VALUE), 2) FROM {{ ref('mart_customers') }} WHERE CUSTOMER_ID IS NOT NULL) as AVG_CLV,
    
    -- Order Metrics
    (SELECT COUNT(DISTINCT ORDER_ID) FROM {{ ref('mart_orders') }}) as TOTAL_ORDERS,
    (SELECT ROUND(SUM(ORDER_TOTAL), 2) FROM {{ ref('mart_orders') }}) as TOTAL_REVENUE,
    (SELECT ROUND(AVG(ORDER_TOTAL), 2) FROM {{ ref('mart_orders') }}) as AVG_ORDER_VALUE,
    (SELECT ROUND(SUM(ORDER_TAX_PAID), 2) FROM {{ ref('mart_orders') }}) as TOTAL_TAX_COLLECTED,
    
    -- Product Metrics
    (SELECT COUNT(DISTINCT ITEM_SKU) FROM {{ ref('mart_products') }} WHERE ITEM_SKU IS NOT NULL) as UNIQUE_PRODUCTS,
    (SELECT SUM(TOTAL_ITEMS_SOLD) FROM {{ ref('mart_products') }} WHERE ITEM_SKU IS NOT NULL) as TOTAL_UNITS_SOLD;

-- ============================================================================

-- 2. REVENUE CONCENTRATION ANALYSIS
-- ABC analysis - identify critical revenue drivers
WITH PRODUCT_CONTRIBUTION AS (
    SELECT 
        ITEM_SKU,
        PRODUCT_NAME,
        PRODUCT_REVENUE,
        SUM(PRODUCT_REVENUE) OVER (ORDER BY PRODUCT_REVENUE DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as CUMULATIVE_REVENUE,
        SUM(PRODUCT_REVENUE) OVER () as TOTAL_REVENUE,
        ROW_NUMBER() OVER (ORDER BY PRODUCT_REVENUE DESC) as PRODUCT_RANK
    FROM {{ ref('mart_products') }}
    WHERE ITEM_SKU IS NOT NULL
)
SELECT 
    PRODUCT_RANK,
    ITEM_SKU,
    PRODUCT_NAME,
    PRODUCT_REVENUE,
    ROUND(100.0 * PRODUCT_REVENUE / TOTAL_REVENUE, 2) as PERCENT_OF_REVENUE,
    ROUND(100.0 * CUMULATIVE_REVENUE / TOTAL_REVENUE, 2) as CUMULATIVE_PERCENT,
    CASE 
        WHEN ROUND(100.0 * CUMULATIVE_REVENUE / TOTAL_REVENUE, 2) <= 80 THEN 'A - Critical'
        WHEN ROUND(100.0 * CUMULATIVE_REVENUE / TOTAL_REVENUE, 2) <= 95 THEN 'B - Important'
        ELSE 'C - Minor'
    END as PARETO_CLASSIFICATION
FROM PRODUCT_CONTRIBUTION
WHERE PRODUCT_RANK <= 20;

-- ============================================================================

-- 3. SALES FUNNEL ANALYSIS
-- Track customer journey from first order to repeat purchase
WITH CUSTOMER_JOURNEY AS (
    SELECT 
        TOTAL_ORDERS,
        COUNT(DISTINCT CUSTOMER_ID) as CUSTOMER_COUNT,
        ROUND(100.0 * COUNT(DISTINCT CUSTOMER_ID) / SUM(COUNT(DISTINCT CUSTOMER_ID)) OVER (), 2) as PERCENT_OF_TOTAL
    FROM {{ ref('mart_customers') }}
    WHERE CUSTOMER_ID IS NOT NULL
    GROUP BY TOTAL_ORDERS
)
SELECT 
    CASE 
        WHEN TOTAL_ORDERS = 1 THEN 'One-Time Buyers'
        WHEN TOTAL_ORDERS BETWEEN 2 AND 3 THEN 'Repeat Buyers (2-3)'
        WHEN TOTAL_ORDERS BETWEEN 4 AND 10 THEN 'Loyal (4-10)'
        ELSE 'Very Loyal (10+)'
    END as CUSTOMER_TIER,
    SUM(CUSTOMER_COUNT) as CUSTOMER_COUNT,
    ROUND(SUM(PERCENT_OF_TOTAL), 2) as PERCENT_OF_CUSTOMERS,
    ROUND(SUM(CUSTOMER_COUNT) * 100 / 
        (SELECT COUNT(DISTINCT CUSTOMER_ID) FROM {{ ref('mart_customers') }} WHERE TOTAL_ORDERS = 1), 2) as CONVERSION_FROM_ONE_TIME_PERCENT
FROM CUSTOMER_JOURNEY
GROUP BY CUSTOMER_TIER
ORDER BY CUSTOMER_COUNT DESC;

-- ============================================================================

-- 4. CUSTOMER VALUE BY COHORT
-- Track customer value progression by acquisition month
WITH COHORT_VALUE AS (
    SELECT 
        DATE_TRUNC(MONTH, FIRST_ORDER_DATE) as ACQUISITION_MONTH,
        COUNT(DISTINCT CUSTOMER_ID) as CUSTOMERS_ACQUIRED,
        ROUND(SUM(CUSTOMER_LIFETIME_VALUE) / NULLIF(COUNT(DISTINCT CUSTOMER_ID), 0), 2) as AVG_CLV,
        SUM(CUSTOMER_LIFETIME_VALUE) as COHORT_TOTAL_VALUE,
        ROUND(AVG(TOTAL_ORDERS), 2) as AVG_ORDERS,
        ROUND(AVG(CUSTOMER_TENURE_DAYS), 0) as AVG_DAYS_AS_CUSTOMER
    FROM {{ ref('mart_customers') }}
    WHERE CUSTOMER_ID IS NOT NULL
    GROUP BY DATE_TRUNC(MONTH, FIRST_ORDER_DATE)
)
SELECT 
    ACQUISITION_MONTH,
    CUSTOMERS_ACQUIRED,
    AVG_CLV,
    COHORT_TOTAL_VALUE,
    AVG_ORDERS,
    AVG_DAYS_AS_CUSTOMER,
    ROUND(COHORT_TOTAL_VALUE / NULLIF(CUSTOMERS_ACQUIRED, 0), 2) as VALUE_PER_CUSTOMER_ACQUIRED
FROM COHORT_VALUE
ORDER BY ACQUISITION_MONTH DESC;

-- ============================================================================

-- 5. PRODUCT PERFORMANCE SCORECARD
-- Comprehensive product metrics for decision making
SELECT 
    ITEM_SKU,
    PRODUCT_NAME,
    PRODUCT_TYPE,
    ROUND(PRODUCT_PRICE, 2) as PRODUCT_PRICE,
    REVENUE_RANK,
    POPULARITY_RANK,
    TOTAL_ITEMS_SOLD,
    ORDERS_CONTAINING_PRODUCT,
    ROUND(PRODUCT_REVENUE, 2) as PRODUCT_REVENUE,
    ROUND(AVG_REVENUE_PER_UNIT, 2) as AVG_UNIT_PRICE,
    PRODUCT_PERFORMANCE_TIER,
    PRODUCT_POPULARITY_TIER,
    CASE 
        WHEN REVENUE_RANK <= 10 AND POPULARITY_RANK <= 10 THEN 'STARS'
        WHEN REVENUE_RANK <= 20 AND POPULARITY_RANK <= 20 THEN 'STRONG'
        WHEN PRODUCT_PERFORMANCE_TIER = 'Low Performer' THEN 'REVIEW'
        ELSE 'STANDARD'
    END as RECOMMENDATION
FROM {{ ref('mart_products') }}
WHERE ITEM_SKU IS NOT NULL
ORDER BY REVENUE_RANK ASC
LIMIT 30;

-- ============================================================================

-- 6. CUSTOMER SEGMENTATION PERFORMANCE
-- Compare metrics across customer segments
SELECT 
    CUSTOMER_SEGMENT,
    COUNT(DISTINCT CUSTOMER_ID) as SEGMENT_SIZE,
    ROUND(100.0 * COUNT(DISTINCT CUSTOMER_ID) / SUM(COUNT(DISTINCT CUSTOMER_ID)) OVER (), 2) as PERCENT_OF_CUSTOMERS,
    ROUND(SUM(CUSTOMER_LIFETIME_VALUE), 2) as SEGMENT_VALUE,
    ROUND(100.0 * SUM(CUSTOMER_LIFETIME_VALUE) / SUM(SUM(CUSTOMER_LIFETIME_VALUE)) OVER (), 2) as PERCENT_OF_REVENUE,
    ROUND(AVG(CUSTOMER_LIFETIME_VALUE), 2) as AVG_CLV,
    ROUND(AVG(TOTAL_ORDERS), 2) as AVG_ORDERS,
    ROUND(AVG(AVG_ORDER_VALUE), 2) as AVG_AOV,
    COUNT(DISTINCT CASE WHEN CUSTOMER_STATUS = 'Active' THEN CUSTOMER_ID END) as ACTIVE_CUSTOMERS,
    COUNT(DISTINCT CASE WHEN CUSTOMER_STATUS = 'At Risk' THEN CUSTOMER_ID END) as AT_RISK_CUSTOMERS
FROM {{ ref('mart_customers') }}
WHERE CUSTOMER_ID IS NOT NULL
GROUP BY CUSTOMER_SEGMENT
ORDER BY SEGMENT_VALUE DESC;

-- ============================================================================

-- 7. CHANNEL/STORE PERFORMANCE COMPARISON
-- Compare performance metrics across stores
SELECT 
    ORDER_STORE_ID,
    COUNT(DISTINCT ORDER_ID) as TOTAL_ORDERS,
    COUNT(DISTINCT ORDER_CUSTOMER) as UNIQUE_CUSTOMERS,
    ROUND(SUM(ORDER_TOTAL), 2) as TOTAL_REVENUE,
    ROUND(AVG(ORDER_TOTAL), 2) as AVG_ORDER_VALUE,
    ROUND(SUM(ORDER_TOTAL) / NULLIF(COUNT(DISTINCT ORDER_CUSTOMER), 0), 2) as REVENUE_PER_CUSTOMER,
    ROUND(COUNT(DISTINCT ORDER_ID) / NULLIF(COUNT(DISTINCT ORDER_CUSTOMER), 0), 2) as ORDERS_PER_CUSTOMER,
    ROUND(SUM(ITEMS_IN_ORDER) / NULLIF(COUNT(DISTINCT ORDER_ID), 0), 2) as AVG_ITEMS_PER_ORDER,
    MIN(CAST(ORDERED_AT AS DATE)) as FIRST_ORDER_DATE,
    MAX(CAST(ORDERED_AT AS DATE)) as LAST_ORDER_DATE,
    DATEDIFF(DAY, MIN(CAST(ORDERED_AT AS DATE)), MAX(CAST(ORDERED_AT AS DATE))) as DAYS_OPERATING
FROM {{ ref('mart_orders') }}
WHERE ORDER_STORE_ID IS NOT NULL
GROUP BY ORDER_STORE_ID
ORDER BY TOTAL_REVENUE DESC;
