-- RAW_TWEETS Table DDL
-- Jaffle Shop Customer Tweets/Social Media Data

CREATE TABLE IF NOT EXISTS RAW_TWEETS (
    ID VARCHAR NOT NULL,
    USER_ID VARCHAR NOT NULL,
    TWEETED_AT VARCHAR,
    CONTENT VARCHAR
);
