snapshots:
  - name: order_status_snapshot
    description: "Snapshot of order statuses over time"
    relation: source('snapshot_demo', 'ord_status')
    config:
      target_database: SNAPSHOT_DEMO
      target_schema: snapshots_tables
      alias : order_status_snapshot_ts_strategy_demo_yaml
      unique_key: ORD_ID
      strategy: timestamp
      updated_at: ORD_STATUS_UPDATE_TS
      hard_deletes: invalidate  